#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# LIOS VM Setup Script — run this once after SSH-ing into your Azure VM
# Ubuntu 22.04 LTS | B2ats v2 (AMD, 4GB RAM)
#
# Usage:
#   chmod +x setup_vm.sh
#   ./setup_vm.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

REPO_URL="${LIOS_REPO_URL:-}"          # Set before running: export LIOS_REPO_URL=https://github.com/YOU/LIOS
APP_DIR="/app/lios"
NGROK_DOMAIN="${NGROK_DOMAIN:-nuptials-flame-steadily.ngrok-free.dev}"
NGROK_TOKEN="${NGROK_TOKEN:-}"         # Set before running: export NGROK_TOKEN=your_token
OLLAMA_MODEL="${OLLAMA_MODEL:-qwen2.5:3b}"   # 1.9GB — fits safely in 4GB RAM

echo "──────────────────────────────────────────"
echo " LIOS VM Setup"
echo " App dir   : $APP_DIR"
echo " Ollama    : $OLLAMA_MODEL"
echo " ngrok     : $NGROK_DOMAIN"
echo "──────────────────────────────────────────"

# ── 1. System packages ────────────────────────────────────────────────────────
echo "[1/9] Installing system packages..."
sudo apt-get update -qq
sudo apt-get install -y --no-install-recommends \
    python3.11 python3.11-venv python3.11-dev \
    python3-pip git curl nginx unzip build-essential libgomp1

# ── 2. Swap (critical: prevents OOM when Ollama loads the model) ──────────────
echo "[2/9] Setting up 4GB swap..."
if [ ! -f /swapfile ]; then
    sudo fallocate -l 4G /swapfile
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile
    sudo swapon /swapfile
    echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
    echo "Swap created."
else
    echo "Swap already exists, skipping."
fi

# ── 3. Mount 64GB data disk ───────────────────────────────────────────────────
echo "[3/9] Checking data disk..."
# Azure names extra disks /dev/sdc or /dev/disk/azure/scsi1/lun0
# If already mounted at /app, skip this step
if ! mountpoint -q /app 2>/dev/null; then
    DATA_DISK=$(lsblk -o NAME,SIZE,MOUNTPOINT | grep -E "^sdc|^sdb" | grep -v "/" | awk '{print "/dev/"$1}' | head -1)
    if [ -n "$DATA_DISK" ]; then
        echo "Formatting and mounting $DATA_DISK → /app"
        sudo mkfs.ext4 -F "$DATA_DISK"
        sudo mkdir -p /app
        sudo mount "$DATA_DISK" /app
        echo "$DATA_DISK /app ext4 defaults,nofail 0 2" | sudo tee -a /etc/fstab
    else
        echo "No extra disk found — using OS disk (fine for dev)."
        sudo mkdir -p /app
    fi
fi
sudo chown -R "$USER":"$USER" /app

# ── 4. Clone LIOS ─────────────────────────────────────────────────────────────
echo "[4/9] Cloning LIOS..."
if [ -n "$REPO_URL" ]; then
    if [ -d "$APP_DIR/.git" ]; then
        cd "$APP_DIR" && git pull
    else
        git clone "$REPO_URL" "$APP_DIR"
    fi
else
    echo "LIOS_REPO_URL not set — skipping clone."
    echo "  → Manually copy your project to $APP_DIR"
    mkdir -p "$APP_DIR"
fi

# ── 5. Python environment ─────────────────────────────────────────────────────
echo "[5/9] Setting up Python venv..."
cd "$APP_DIR"
python3.11 -m venv venv
source venv/bin/activate
pip install --upgrade pip -q
pip install -r requirements.txt -q
echo "Python env ready."

# ── 6. Install Ollama ─────────────────────────────────────────────────────────
echo "[6/9] Installing Ollama..."
if ! command -v ollama &>/dev/null; then
    curl -fsSL https://ollama.com/install.sh | sh
    echo "Ollama installed."
else
    echo "Ollama already installed."
fi

# Start Ollama so we can pull the model
sudo systemctl enable ollama
sudo systemctl start ollama
sleep 3  # wait for Ollama to be ready

echo "Pulling model: $OLLAMA_MODEL (this takes a few minutes)..."
ollama pull "$OLLAMA_MODEL"
echo "Model ready."

# ── 7. Install ngrok ──────────────────────────────────────────────────────────
echo "[7/9] Installing ngrok..."
if ! command -v ngrok &>/dev/null; then
    curl -fsSL https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz | sudo tar -xz -C /usr/local/bin
    echo "ngrok installed."
else
    echo "ngrok already installed."
fi

if [ -n "$NGROK_TOKEN" ]; then
    ngrok config add-authtoken "$NGROK_TOKEN"
    echo "ngrok token configured."
else
    echo "NGROK_TOKEN not set — run: ngrok config add-authtoken YOUR_TOKEN"
fi

# ── 8. Create .env ────────────────────────────────────────────────────────────
echo "[8/9] Creating .env..."
if [ ! -f "$APP_DIR/.env" ]; then
    cat > "$APP_DIR/.env" << ENVEOF
# LIOS production environment — generated by setup_vm.sh

LIOS_LLM_ENABLED=true
LIOS_LLM_PROVIDER=openai_compatible
LIOS_LLM_BASE_URL=http://localhost:11434/v1
LIOS_LLM_MODEL=${OLLAMA_MODEL}
LIOS_LLM_API_KEY=ollama

LIOS_API_KEY=CHANGE_THIS_TO_A_STRONG_RANDOM_SECRET
LIOS_CORS_ALLOWED_ORIGINS=https://${NGROK_DOMAIN}

LIOS_CHAT_STORE_BACKEND=sqlite
LIOS_LOG_LEVEL=INFO
ENVEOF
    echo ".env created — edit $APP_DIR/.env to set LIOS_API_KEY"
else
    echo ".env already exists, skipping."
fi

# ── 9. Systemd services ───────────────────────────────────────────────────────
echo "[9/9] Creating systemd services..."

# LIOS FastAPI service
sudo tee /etc/systemd/system/lios.service > /dev/null << SERVICEEOF
[Unit]
Description=LIOS FastAPI Server
After=network.target ollama.service
Wants=ollama.service

[Service]
User=${USER}
WorkingDirectory=${APP_DIR}
EnvironmentFile=${APP_DIR}/.env
ExecStart=${APP_DIR}/venv/bin/uvicorn lios.main:app --host 127.0.0.1 --port 8000 --workers 1
Restart=always
RestartSec=5
StandardOutput=append:/var/log/lios.log
StandardError=append:/var/log/lios.log

[Install]
WantedBy=multi-user.target
SERVICEEOF

# ngrok tunnel service
sudo tee /etc/systemd/system/ngrok.service > /dev/null << SERVICEEOF
[Unit]
Description=ngrok tunnel for LIOS
After=network.target lios.service

[Service]
User=${USER}
ExecStart=/usr/local/bin/ngrok http 8000 --domain=${NGROK_DOMAIN} --log=stdout
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
SERVICEEOF

sudo systemctl daemon-reload
sudo systemctl enable lios ngrok
sudo systemctl start lios
sleep 3
sudo systemctl start ngrok

echo ""
echo "══════════════════════════════════════════"
echo " Setup complete!"
echo ""
echo " Services status:"
sudo systemctl is-active lios    && echo "  ✓ lios    → running" || echo "  ✗ lios    → FAILED"
sudo systemctl is-active ollama  && echo "  ✓ ollama  → running" || echo "  ✗ ollama  → FAILED"
sudo systemctl is-active ngrok   && echo "  ✓ ngrok   → running" || echo "  ✗ ngrok   → FAILED"
echo ""
echo " Test your server:"
echo "   curl https://${NGROK_DOMAIN}/health"
echo ""
echo " View logs:"
echo "   sudo journalctl -u lios -f"
echo "   sudo journalctl -u ngrok -f"
echo "   sudo tail -f /var/log/lios.log"
echo ""
echo " ⚠  Remember to edit .env and set LIOS_API_KEY:"
echo "   nano ${APP_DIR}/.env"
echo "══════════════════════════════════════════"
